In [1]:
# importing library

import numpy as np     # linear algebra
import pandas as pd    # data processing

In [2]:
dpath = "../input/titanic-datasets/"

In [3]:
train_titanic = pd.read_csv(dpath + "train.csv")

In [4]:
test_titanic = pd.read_csv(dpath + "test.csv")

## Training Dataset

In [5]:
train_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:
# random 10 sample data points of training data
train_titanic.sample(10)

PassengerId  Survived  Pclass  \
403          404         0       3   
555          556         0       1   
473          474         1       2   
303          304         1       2   
477          478         0       3   
765          766         1       1   
381          382         1       3   
564          565         0       3   
256          257         1       1   
404          405         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
403                Hakkarainen, Mr. Pekka Pietari    male  28.0      1      0   
555                            Wright, Mr. George    male  62.0      0      0   
473  Jerwan, Mrs. Amin S (Marie Marthe Thuillard)  female  23.0      0      0   
303                           Keane, Miss. Nora A  female   NaN      0      0   
477                     Braund, Mr. Lewis Richard    male  29.0      1      0   
765          Hogeboom, Mrs. John C (Anna Andrews)  female  51.0      1      0   
381                   Nakid, Miss. Maria ("Mary")  female   1.0      0      2   
564                Meanwell, Miss. (Marion Ogden)  female   NaN      0      0   
256                Thorne, Mrs. Gertrude Maybelle  female   NaN      0      0   
404                       Oreskovic, Miss. Marija  female  20.0      0      0   

                Ticket     Fare Cabin Embarked  
403   STON/O2. 3101279  15.8500   NaN        S  
555             113807  26.5500   NaN        S  
473    SC/AH Basle 541  13.7917     D        C  
303             226593  12.3500  E101        Q  
477               3460   7.0458   NaN        S  
765              13502  77.9583   D11        S  
381               2653  15.7417   NaN        C  
564  SOTON/O.Q. 392087   8.0500   NaN        S  
256           PC 17585  79.2000   NaN        C  
404             315096   8.6625   NaN        S

In [7]:
train_titanic.shape

(891, 12)

In [8]:
train_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
# basic information of dataset
train_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [10]:
# columnwise total null values
train_titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
# statistical inforamtion of numeric data
train_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
train_titanic.PassengerId

0        1
1        2
2        3
3        4
4        5
      ... 
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [13]:
# removing PassengerId column because it is not useful in any analysis
train_titanic.drop('PassengerId',inplace=True, axis=1)

In [14]:
train_titanic.Survived.unique()    # unique class present in Survived column

array([0, 1])

In [15]:
train_titanic.Survived.value_counts()     # value count of unique class in Survived column

0    549
1    342
Name: Survived, dtype: int64

In [16]:
train_titanic.Pclass.unique()       # unique class present in Pclass column

array([3, 1, 2])

In [17]:
train_titanic.Pclass.value_counts()       # value count of unique class in Pclass column

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [18]:
train_titanic.Name.nunique()        # count unique name from Name column

891

In [19]:
# removing Name column because each name is unique and it won't be used in any analysis
train_titanic.drop("Name", axis=1, inplace=True)

In [20]:
train_titanic.Sex.unique()       # unique class present in Sex column

array(['male', 'female'], dtype=object)

In [21]:
train_titanic.Sex.replace(['male', 'female'], [1,0], inplace=True)      # replacing gender with boolean values

In [22]:
train_titanic.head()

Survived  Pclass  Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
0         0       3    1  22.0      1      0         A/5 21171   7.2500   NaN   
1         1       1    0  38.0      1      0          PC 17599  71.2833   C85   
2         1       3    0  26.0      0      0  STON/O2. 3101282   7.9250   NaN   
3         1       1    0  35.0      1      0            113803  53.1000  C123   
4         0       3    1  35.0      0      0            373450   8.0500   NaN   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S

In [23]:
train_titanic.Age.isnull().sum()

177

In [24]:
train_titanic.Age.mean()

29.69911764705882

In [25]:
train_titanic.Age.median()

28.0

In [26]:
train_titanic.Age.fillna(train_titanic.Age.mean(), inplace = True)        # filling mean of Age column in null value

In [27]:
train_titanic[train_titanic.Age == 0]

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [28]:
train_titanic.Age.dtype

dtype('float64')

In [29]:
train_titanic.Age = train_titanic.Age.astype('int64')         # changing data type of Age column

In [30]:
train_titanic.Age.dtype

dtype('int64')

In [31]:
train_titanic[train_titanic.Age == 0]

Survived  Pclass  Sex  Age  SibSp  Parch  Ticket      Fare    Cabin  \
78          1       2    1    0      0      2  248738   29.0000      NaN   
305         1       1    1    0      1      2  113781  151.5500  C22 C26   
469         1       3    0    0      2      1    2666   19.2583      NaN   
644         1       3    0    0      2      1    2666   19.2583      NaN   
755         1       2    1    0      1      1  250649   14.5000      NaN   
803         1       3    1    0      0      1    2625    8.5167      NaN   
831         1       2    1    0      1      1   29106   18.7500      NaN   

    Embarked  
78         S  
305        S  
469        C  
644        C  
755        S  
803        C  
831        S

In [32]:
train_titanic.Age.mean()

29.544332210998878

In [33]:
train_titanic.Age.replace(0, train_titanic.Age.mean(), inplace = True)        # replacing mean with 0

In [34]:
train_titanic.Age.mean()

29.776442565069573

In [35]:
train_titanic.Age.dtype

dtype('float64')

In [36]:
train_titanic.Age = train_titanic.Age.astype('int64')

In [37]:
train_titanic[train_titanic.Age == 0]

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [38]:
train_titanic.head()

Survived  Pclass  Sex  Age  SibSp  Parch            Ticket     Fare Cabin  \
0         0       3    1   22      1      0         A/5 21171   7.2500   NaN   
1         1       1    0   38      1      0          PC 17599  71.2833   C85   
2         1       3    0   26      0      0  STON/O2. 3101282   7.9250   NaN   
3         1       1    0   35      1      0            113803  53.1000  C123   
4         0       3    1   35      0      0            373450   8.0500   NaN   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S

In [39]:
train_titanic.SibSp.unique()         # unique class present in SibSp column

array([1, 0, 3, 4, 2, 5, 8])

In [40]:
train_titanic.SibSp.value_counts()          # value count of unique class in SibSp column

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

In [41]:
train_titanic.Parch.unique()         # unique class present in Parch column

array([0, 1, 2, 5, 3, 4, 6])

In [42]:
train_titanic.Parch.value_counts()          # value count of unique class in Parch column

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [43]:
train_titanic.Ticket.nunique() 

681

In [44]:
train_titanic.Ticket.value_counts().unique()

array([7, 6, 5, 4, 3, 2, 1])

In [45]:
# here we don't have information of allocation of ticket and services so we can assume that a person having same ticket gets 
# same service so it shouldn't impect on result that's why I am removing this Ticket column 

train_titanic.drop('Ticket', axis = 1, inplace = True)

In [46]:
train_titanic.Fare  # this was working in jupyter notebook as train_titanic.Fare.info() here I removed info() because of error.

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [47]:
train_titanic[train_titanic.Fare == 0]

Survived  Pclass  Sex  Age  SibSp  Parch  Fare Cabin Embarked
179         0       3    1   36      0      0   0.0   NaN        S
263         0       1    1   40      0      0   0.0   B94        S
271         1       3    1   25      0      0   0.0   NaN        S
277         0       2    1   29      0      0   0.0   NaN        S
302         0       3    1   19      0      0   0.0   NaN        S
413         0       2    1   29      0      0   0.0   NaN        S
466         0       2    1   29      0      0   0.0   NaN        S
481         0       2    1   29      0      0   0.0   NaN        S
597         0       3    1   49      0      0   0.0   NaN        S
633         0       1    1   29      0      0   0.0   NaN        S
674         0       2    1   29      0      0   0.0   NaN        S
732         0       2    1   29      0      0   0.0   NaN        S
806         0       1    1   39      0      0   0.0   A36        S
815         0       1    1   29      0      0   0.0  B102        S
822         0       1    1   38      0      0   0.0   NaN        S

In [48]:
train_titanic.Fare.mean()

32.204207968574636

In [49]:
train_titanic.Fare.replace(0, train_titanic.Fare.mean(), inplace = True)      # replacing mean of Fare column with 0

In [50]:
train_titanic.Fare.mean()

32.74636635188397

In [51]:
train_titanic.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [52]:
train_titanic.Cabin    # this was working in jupyter notebook as train_titanic.Cabin.info() here I removed info() because of error.

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [53]:
# there is no use of cabin in predicting so better to drop.
train_titanic.drop('Cabin', axis = 1, inplace = True)

In [54]:
train_titanic.Embarked.unique()        # unique class present in Embarked column

array(['S', 'C', 'Q', nan], dtype=object)

In [55]:
train_titanic.Embarked.value_counts()          # value count of unique class in Embarked column

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [56]:
train_titanic.Embarked.mode()

0    S
dtype: object

In [57]:
train_titanic.Embarked.fillna('S', inplace=True)        # Filling 'S' in place of blank(nan)

In [58]:
train_titanic.Embarked.replace(['S', 'C', 'Q'], [0, 1, 2], inplace = True)

## Final Train Data

In [59]:
train_titanic

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0           0       3    1   22      1      0   7.2500         0
1           1       1    0   38      1      0  71.2833         1
2           1       3    0   26      0      0   7.9250         0
3           1       1    0   35      1      0  53.1000         0
4           0       3    1   35      0      0   8.0500         0
..        ...     ...  ...  ...    ...    ...      ...       ...
886         0       2    1   27      0      0  13.0000         0
887         1       1    0   19      0      0  30.0000         0
888         0       3    0   29      1      2  23.4500         0
889         1       1    1   26      0      0  30.0000         1
890         0       3    1   32      0      0   7.7500         2

[891 rows x 8 columns]

In [60]:
train_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    int64  
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(1), int64(7)
memory usage: 55.8 KB


In [61]:
test_titanic

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [62]:
test_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [63]:
PassengerId = test_titanic.PassengerId         # initialize PassengerId for upcoming use

In [64]:
test_titanic.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace = True, axis = 1)

In [65]:
test_titanic.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

### Doing same cleaning and manipulation of data as Train dataset

In [66]:
test_titanic.Pclass.unique()

array([3, 2, 1])

In [67]:
test_titanic.Pclass.value_counts()

3    218
1    107
2     93
Name: Pclass, dtype: int64

In [68]:
test_titanic.Sex.unique()

array(['male', 'female'], dtype=object)

In [69]:
test_titanic.Sex.replace(['male', 'female'], [1,0], inplace = True)

In [70]:
test_titanic.Age.mean()

30.272590361445783

In [71]:
test_titanic.Age.fillna(test_titanic.Age.mean(), inplace = True)

In [72]:
test_titanic.Age.dtype

dtype('float64')

In [73]:
test_titanic.Age = test_titanic.Age.astype('int64')

In [74]:
test_titanic.Age.dtype

dtype('int64')

In [75]:
test_titanic[test_titanic.Age == 0]

Pclass  Sex  Age  SibSp  Parch    Fare Embarked
201       3    1    0      0      2  14.400        S
250       2    0    0      1      2  27.750        S
281       3    1    0      1      1  13.775        S
307       3    1    0      0      1   9.350        S
354       3    0    0      1      2  20.575        S

In [76]:
test_titanic.Age.replace(0, int(test_titanic.Age.mean()), inplace = True)

In [77]:
test_titanic.Age.max()

76

In [78]:
test_titanic.SibSp.value_counts()

0    283
1    110
2     14
3      4
4      4
8      2
5      1
Name: SibSp, dtype: int64

In [79]:
test_titanic.SibSp.unique()

array([0, 1, 2, 3, 4, 5, 8])

In [80]:
test_titanic.Parch.unique()

array([0, 1, 3, 2, 4, 6, 5, 9])

In [81]:
test_titanic.Parch.value_counts()

0    324
1     52
2     33
3      3
4      2
9      2
6      1
5      1
Name: Parch, dtype: int64

In [82]:
test_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    int64  
 2   Age       418 non-null    int64  
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(1), int64(5), object(1)
memory usage: 23.0+ KB


In [83]:
test_titanic.Fare    # this was working in jupyter notebook as train_titanic.Fare.info() here I removed info() because of error.

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...   
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [84]:
test_titanic.Fare.fillna(test_titanic.Fare.mean(), inplace = True)

In [85]:
test_titanic.Embarked.unique()

array(['Q', 'S', 'C'], dtype=object)

In [86]:
test_titanic.Embarked.mode()

0    S
dtype: object

In [87]:
test_titanic.Embarked.replace(['S', 'C', 'Q'], [0, 1, 2], inplace = True)

## Final Test Data

In [88]:
test_titanic

Pclass  Sex  Age  SibSp  Parch      Fare  Embarked
0         3    1   34      0      0    7.8292         2
1         3    0   47      1      0    7.0000         0
2         2    1   62      0      0    9.6875         2
3         3    1   27      0      0    8.6625         0
4         3    0   22      1      1   12.2875         0
..      ...  ...  ...    ...    ...       ...       ...
413       3    1   30      0      0    8.0500         0
414       1    0   39      0      0  108.9000         1
415       3    1   38      0      0    7.2500         0
416       3    1   30      0      0    8.0500         0
417       3    1   30      1      1   22.3583         1

[418 rows x 7 columns]

# Machine Learning

## importing libraries

In [89]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import warnings
warnings.filterwarnings('ignore')

In [90]:
X = train_titanic.drop('Survived', axis = 1)
y = train_titanic.Survived

In [91]:
lr_model = LogisticRegression()
dtc_model = DecisionTreeClassifier()
rfc_model = RandomForestClassifier()

### Splitting training data into train set and test sets.

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=42)

### Model Training/Fitting -> Prediction -> Performance Testing

## ***Logistic Regression Model***

In [93]:
lr_model.fit(X_train, y_train)

LogisticRegression()

In [94]:
lr_y_predict = lr_model.predict(X_test)

lr_accuracy = (100 * accuracy_score(y_test, lr_y_predict)).round(2)
print(f"Accuracy of Logistic Regression Model : {lr_accuracy} %", "\n")
print("Confusion Matrix : \n", confusion_matrix(y_test, lr_y_predict), "\n")
print("Classification Report : \n", classification_report(y_test, lr_y_predict),"\n")

Accuracy of Logistic Regression Model : 79.33 % 

Confusion Matrix : 
 [[88 17]
 [20 54]] 

Classification Report : 
               precision    recall  f1-score   support

           0       0.81      0.84      0.83       105
           1       0.76      0.73      0.74        74

    accuracy                           0.79       179
   macro avg       0.79      0.78      0.79       179
weighted avg       0.79      0.79      0.79       179
 



## ***Decision Tree Classifier***

In [95]:
dtc_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [96]:
dtc_y_predict = dtc_model.predict(X_test)

dtc_accuracy = (100 * accuracy_score(y_test, dtc_y_predict)).round(2)
print(f"Accuracy of Decision Tree Model : {dtc_accuracy} % \n" )
print("Confusion Matrix : \n", confusion_matrix(y_test, dtc_y_predict), "\n")
print("Classification Report : \n", classification_report(y_test, dtc_y_predict), "\n")

Accuracy of Decision Tree Model : 77.65 % 

Confusion Matrix : 
 [[84 21]
 [19 55]] 

Classification Report : 
               precision    recall  f1-score   support

           0       0.82      0.80      0.81       105
           1       0.72      0.74      0.73        74

    accuracy                           0.78       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179
 



## ***Random Forest Classifier***

In [97]:
rfc_model.fit(X_train, y_train)

RandomForestClassifier()

In [98]:
rfc_y_predict = rfc_model.predict(X_test)

rfc_accuracy = (100 * accuracy_score(y_test, rfc_y_predict)).round(2)
print(f"Accuracy of Random Forest Model : {rfc_accuracy} % \n")
print("Confusion Matrix : \n", confusion_matrix(y_test, rfc_y_predict), "\n")
print("Classification Report : \n", classification_report(y_test, rfc_y_predict),"\n")

Accuracy of Random Forest Model : 81.01 % 

Confusion Matrix : 
 [[90 15]
 [19 55]] 

Classification Report : 
               precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179
 



### Summary

In [99]:
Model = ['LogisticRegression', 'DecisionTreeClassifier', 'RandomForestClassifier']
Accuracy = [lr_accuracy, dtc_accuracy, rfc_accuracy]

In [100]:
acc_df = pd.DataFrame({'Model': Model, 'Accuracy': Accuracy})
acc_df.sort_values(by = 'Accuracy', ascending=False, ignore_index=True)

Model  Accuracy
0  RandomForestClassifier     81.01
1      LogisticRegression     79.33
2  DecisionTreeClassifier     77.65

## Prediction output for the test dataset using Random Forest Classifier

In [101]:
rfc_y_predict_final = rfc_model.predict(test_titanic)

In [102]:
result = pd.DataFrame({'PassengerId': PassengerId, 'Survived': rfc_y_predict_final})

In [103]:
result

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         1
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [104]:
result.to_csv('result.zip', index = False, compression = {'method':'zip', 'archive_name':'result.csv'})